### PR TITLE
Use custom font

### PR DESCRIPTION
**Pull request by hamirmahal**
This should close issue #35 by adding the custom font requested in that issue.

This commit was originally in [Design-Updates](https://github.com/amilajack/freesound-player/tree/Design-Updates), but I have since moved the commit here for faster integration into `master` and undid the commit in that branch for a cleaner history.

### CODE REVIEW

**Comment by hamirmahal** [comment]
Just as a friendly reminder, we still have to deploy this to see the changes on the live site.

I wanted to make sure everything was okay before doing that, first, though.

**Comment by hamirmahal** [comment]
> Just as a friendly reminder, we still have to deploy this to see the changes on the live site.
> 
> I wanted to make sure everything was okay before doing that, first, though.

@amilajack I tried doing `yarn deploy` to get these changes to appear on the live site, but it doesn't look like the `index.html` file in the `gh-pages` branch of this repository updated. Did I mess something up somewhere?

**Comment by amilajack** [comment]
Are you getting any error messages?

**Comment by amilajack** [comment]
Nice!. Also a note for future PR's: convention is to now merge your own pull requests until you get PR approved by reviewer.That allows you to update the code to reflect the feedback.

**Comment by hamirmahal** [comment]
> Nice!. Also a note for future PR's: convention is to now merge your own pull requests until you get PR approved by reviewer.That allows you to update the code to reflect the feedback.

That makes sense. I'll keep that in mind for next time.

> Are you getting any error messages?

None that I recall. I force-pushed the last working commit for the `gh-pages` branch so that there's less clutter in the commit history. For some strange reason, it looked like everything built to a new folder after I ran `yarn deploy`, and it left all the other files unchanged, ultimately resulting in a live webpage with no visible UI changes despite the custom font update. I'll give it some more consideration.

**Comment by hamirmahal** [comment]
The commits in this branch ended up not doing the trick. #46 handles the changes this pull request set out to do.

**Pull request merged**
