### PR TITLE
close #35 by adding extra bold and medium variants of Mplus 1p

### LINKED ISSUE #35: ui: redesign implementation: use custom font
The current font is different from the one in the UI design, which is [Mplus 1p](https://fonts.google.com/specimen/M+PLUS+1p).

### 1. Add the `link` tags to the `head` tag:

Screen Shot 2020-09-07 at 5 36 59 PM

### 2. Import both fonts (extra bold and medium variants)

Screen Shot 2020-09-17 at 10 36 49 PM
Screen Shot 2020-09-17 at 10 36 53 PM

### 3. Enable the following styles:

```css
body {
  font-family: 'M PLUS 1p', sans-serif;
}

h1, h1, h3, h4, h5, h6 {
  font-weight: bold;
}
```

### PR DESCRIPTION
**Pull request by hamirmahal**
Does this take care of #35?

### CODE REVIEW

**Comment by hamirmahal** [comment]
How do we use netlify to preview this?

**Comment by hamirmahal** [comment]
> How do we use netlify to preview this?

Oh, neat! We can just look right at the checks for the preview link. Found out by reading the below link.

https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

**Comment by hamirmahal** [comment]
> How do we use netlify to preview this?

Oh, neat! We can just look right at the checks for the preview link.

Found out by reading this on the Netlify site: [To help you discover Deploy Previews, we put those links where it helps your team the most, directly in the pull request as commit statuses:](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)

**Comment by hamirmahal** [comment]
> How do we use Netlify to preview pull requests?

Never mind! They explain it on their site.

[To help you discover Deploy Previews, we put those links where it helps your team the most, directly in the pull request as commit statuses:](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)

where to view Netlify preview

**Review by amilajack — APPROVED** [review]
yup, that does it!

**Comment by hamirmahal** [comment]
Awesome! Sounds good.

**Comment by hamirmahal** [comment]
Awesome! That's good to hear.

**Pull request merged**
