### PR TITLE
Toggle between play and pause icons fixed

### LINKED ISSUE #76: feat: replace "Pause" text with ionicon
Currently, while a sound plays, text saying "Pause" appears. I think we should replace that with a pause icon from the ionicon library.

We can see the current appearance of the Play/Pause area while a sound plays, below.

Screen Shot 2020-09-27 at 6 36 57 PM

### PR DESCRIPTION
**Pull request by akshara-sun**
closes #76

### CODE REVIEW

**Comment by akshara-sun** [comment]
fixes #76

**Review by amilajack — APPROVED** [review]
This is great! Nice job 😃

**Comment by amilajack** [comment]
@akshara-sun can you please update description to include which issue this closes

**Comment by akshara-sun** [comment]
> @akshara-sun can you please update description to include which issue this closes

whoops! I commented the issue instead of adding to the description! Let me do that now!

**Comment by akshara-sun** [comment]
> @akshara-sun can you please update description to include which issue this closes

done! the issue is also linked to the PR (I used the new "Linked Issues" feature to do this) so even I didn't add the issue number in the description and you closed this PR, it would close the issue automatically! I'll make sure to do both next time just in case 😉 Thanks!

**Comment by amilajack** [comment]
Yea that's a pretty new github feature I'm not very used to. As a slight preference, I think keeping the issue number also in the description provides slightly better visibility

**Pull request merged**
