### PR TITLE
 styles icons in pack and similar lists; closes #94

### LINKED ISSUE #94: ui: redesign implementation: sound list icons
To-do:

- [x] import icons into sound-list 
- [ ] make play/pause button work on all tracks in the list 
- [ ] style and make download button also functional on each track 

*Follow-up to issue #93*

### PR DESCRIPTION
**Pull request by akshara-sun**
Closes #94 

To-do:
- [x] Create space on the right side of the play button so the number of plays can show up.
- [x] opacity fixes
- [x] hide play button if not hovering over item
- [x] hardcode dummy data
- [x] hide icons on `sm` viewport

## Current

Screen Shot 2020-11-09 at 12 53 04 PM

## Figma
Screen Shot 2020-11-09 at 12 54 39 PM

### CODE REVIEW

**Review by amilajack — CHANGES_REQUESTED** [review]
- **opacity needs to be 0.5 if not hovering over list item**
Screen Shot 2020-11-09 at 1 00 42 PM

- **play button needs to be hidden of not hovering over list item**
Screen Shot 2020-11-09 at 1 02 06 PM

**Comment by amilajack** [comment]
## New Design
Screen Shot 2020-11-09 at 1 18 50 PM

**Comment by amilajack** [comment]
Try watching this https://tailwindcss.com/course/hover-focus-and-active-styles

**Comment by akshara-sun** [comment]
In the current version, the sound list icons and the play buttons become fully opaque **only** when you hover _near_ them. I tried implementing [this](https://tailwindcss.com/docs/pseudo-class-variants#group-hover) but it didn't seem to work.

**Review by amilajack — CHANGES_REQUESTED** [review]
Icons need to be hidden on mobile

Screen Shot 2020-11-10 at 12 36 02 PM

**Review by amilajack — CHANGES_REQUESTED** [review]
Great job! Just some small changes that need to be made. We need to hardcode some values for the values which correspond to the icons:

Screen Shot 2020-11-10 at 9 17 34 PM

The hardcoded dummy text should also be hidden on sm viewport size similar to the icons.

**Comment by akshara-sun** [comment]
@amilajack I hardcoded some dummy stats but they are not in line with the icons, will work on that tomorrow.

**Comment by amilajack** [comment]
You might be able to fix the alignment by wrapping them in a span

**Comment by akshara-sun** [comment]
> You might be able to fix the alignment by wrapping the hardcoded text in a span

I tried using span but it didn't work so maybe I did something wrong

**Comment by amilajack** [comment]
@akshara-sun actually i tried the span too and it didn't work for me either 😆

**Comment by amilajack** [comment]
Found it. You need to use `hidden sm:flex ` instead of `hidden sm:block`. It was displaying a block element before because `sm:block` is more specificity than `flex`. Higher specificity wins in CSS.

**Comment by amilajack** [comment]
Merging this to prevent possible merge conflicts. Lets add the fixes in a followup PR

**Pull request merged**
